"""add column to students table

Revision ID: 023472a741fb
Revises: a2ef11a3f35b
Create Date: 2025-08-01 01:40:56.916559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023472a741fb'
down_revision: Union[str, Sequence[str], None] = 'a2ef11a3f35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('educational_level', sa.String(), nullable=True))
    op.add_column('students', sa.Column('field_of_study', sa.String(), nullable=True))
    op.add_column('students', sa.Column('semester_or_year', sa.String(), nullable=True))
    op.drop_column('students', 'major')
    op.drop_column('students', 'academic_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('academic_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'semester_or_year')
    op.drop_column('students', 'field_of_study')
    op.drop_column('students', 'educational_level')
    # ### end Alembic commands ###
