"""add notification

Revision ID: 44b72ff3e5fd
Revises: 762f9bcab86d
Create Date: 2025-07-31 20:16:01.712708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b72ff3e5fd'
down_revision: Union[str, Sequence[str], None] = '762f9bcab86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('read', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'notification_id')
    op.drop_column('notifications', 'timestamp')
    op.drop_column('notifications', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('status', postgresql.ENUM('unread', 'read', name='notification_status_enum'), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('notification_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['userid'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'read')
    op.drop_column('notifications', 'id')
    # ### end Alembic commands ###
