"""add counselor_id to recommendations

Revision ID: 762f9bcab86d
Revises: f6abb02b920c
Create Date: 2025-07-31 16:35:31.792701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762f9bcab86d'
down_revision: Union[str, Sequence[str], None] = 'f6abb02b920c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('recommendations', sa.Column('counselor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recommendations', 'counselors', ['counselor_id'], ['counselor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_column('recommendations', 'counselor_id')
    op.alter_column('feedback', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
