"""add cascade

Revision ID: ee405289e1f0
Revises: 45f6a6023467
Create Date: 2025-08-02 00:32:05.717034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee405289e1f0'
down_revision: Union[str, Sequence[str], None] = '45f6a6023467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('counselors_user_id_fkey'), 'counselors', type_='foreignkey')
    op.create_foreign_key(None, 'counselors', 'users', ['user_id'], ['userid'], ondelete='CASCADE')
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['userid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['userid'])
    op.drop_constraint(None, 'counselors', type_='foreignkey')
    op.create_foreign_key(op.f('counselors_user_id_fkey'), 'counselors', 'users', ['user_id'], ['userid'])
    # ### end Alembic commands ###
