"""add score to study_plans

Revision ID: f6abb02b920c
Revises: 1085e95347e5
Create Date: 2025-07-30 22:14:18.400315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6abb02b920c'
down_revision: Union[str, Sequence[str], None] = '1085e95347e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_plans', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_plans', 'score')
    # ### end Alembic commands ###
